### PR TITLE
Add --static-folder

### PR DESCRIPTION
**Pull request by NotNite**
Makes running Plogon on non-hircine development environments possible. Also fixes a hardcoded Windows-only named pipe and made the entrypoint script executable (lmao).

### CODE REVIEW

**Comment by philpax** [comment]
lgtm, but I think we should set up CI before we merge this, just to have that beautiful green tick. Do you mind setting that up in another PR?

**Comment by goaaats** [comment]
Think having docker images on ghcr would be good, you can probably just copy in a .NET dockerfile + actions set up, there should be one in the operator repo

**Comment by NotNite** [comment]
I don't think CI would work without this PR? The Windows pipe is still hardcoded, and the file path is still hardcoded to goat's machine.

**Comment by philpax** [comment]
Good point, could maybe be a little naughty and just get CI working in this PR?

**Comment by NotNite** [comment]
Not sure if I'm entirely ready to tackle that yet (not too sure what I need to do tbqh). Also I'm a docker noob so the git history will be VERY messy - not a good idea.

**Comment by philpax** [comment]
That shouldn't be too bad - it'll be a combination of https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action and https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net.

The Git history is fine, we can always clean it up afterwards (rebase interactive isn't too bad once you get used to it.) Give it a shot!

**Comment by NotNite** [comment]
I've got some basic CI to build Plogon set up - nothing fancy. Is this good?

**Comment by philpax** [comment]
lgtm, @goaaats can merge once he's happy

**Review by goaaats — APPROVED** [review]

**Pull request merged**
