### PR TITLE
Use GitHub and GitLab diff url

### LINKED ISSUE #23: Use platform-native diffs when available
If GitHub, create an URL to `https://github.com/username/repo/compare/old..new`. Not sure what the GL equivalent is.

The GH interface is nicer to use for reviewing code than raw diffs in hast.

### PR DESCRIPTION
**Pull request by wolfcomp**
This fixes #23 for GitHub and GitLab

### CODE REVIEW

**Comment by wolfcomp** [comment]
Any feedback on this?

**Comment by philpax** [comment]
This looks good to me so I'm going to merge it.

**Comment by philpax** [comment]
Alright, we've had our first oddity: 

https://github.com/goatcorp/DalamudPluginsD17/pull/402#issuecomment-1250377354

results in `haveCommit` becoming the empty tree commit (as it's empty), which doesn't work with GitHub. I think that's a separate, unrelated issue (it would be nice to get a diff between commits), but the main thing is that it just doesn't work.

I'd suggest opening up another PR to switch to linking to the repo instead of the diff if `haveCommit` doesn't exist?

**Comment by wolfcomp** [comment]
Another method could be to have the diff link to `master%40%7B1day%7D` instead of `4b825dc642cb6eb9a060e54bf8d69288fbee4904` for GitHub. 
Would need to check how this would work with GitLab to fix that one as I'm not sure entirely how that compare system works, as I just found the URL for where it is on the site digging through other repos.

**Comment by wolfcomp** [comment]
Actually found one better that works for both.

Initialize `haveCommit` with the return of `git rev-list --max-parents=0 HEAD` as this will return the first commit in the tree instead of using `emptyTree`

**Comment by goaaats** [comment]
Make sure that the diff actually has the files added in the first commit if you're going to do that, and test it please

**Comment by philpax** [comment]
My preference is still to link to the repo proper for an initial submission (which should be the only time the initial commit doesn't exist.)

Generating diffs is pointless / strictly worse than just looking at the repo with a web UI.

**Pull request merged**
