### PR TITLE
The Plogonening (try 3)

### PR DESCRIPTION
**Pull request by NotNite**
Ended up redoing it because merge conflicts. **MERGE AFTER API 9, I DID NOT TEST THIS IN A PRODUCTION SETUP.**

### CODE REVIEW

**Comment by philpax** [comment]
There's no way to decouple the formatting changes from the functional changes, is there? Hiding whitespace still triggers a diff on linebreak :(

**Comment by NotNite** [comment]
I can theoretically decouple them into multiple commits if that'd be preferred, but to be honest I forgot what exactly I changed at this point.

**Comment by philpax** [comment]
Would it be possible to reformat to the original formatting (I'm guessing not, because the `.editorconfig` was introduced afterwards), extract the local changes, and then reapply the reformat?

**Comment by NotNite** [comment]
No, because the formatting of the original repository was inconsistent with basically every style guide I checked. There is no "reformat to the original formatting" because the original formatting wasn't formatted in the first place.

**Comment by philpax** [comment]
...would it be possible to undo the commit, revert all of the formatting changes manually, make a commit for local fixes, and then reapply the formatting? Having them split apart will make it *much* easier to review / much more likely to land.

**Comment by NotNite** [comment]
Really I can just redo the changes I made from scratch and guess what was wrong, which is probably the easiest. Should I revert the commit on this branch and commit new ones?

**Comment by philpax** [comment]
Up to you! I'd personally `git reset HEAD~` and hack away at it, but a revert is also fine.

**Comment by philpax** [comment]
lol that was quick

**Comment by NotNite** [comment]
ADHD gremlin unmatched power 💪

**Review by philpax — APPROVED** [review]
Seems pretty reasonable to me. Just need a tick from the big man.

**Comment by philpax** [comment]
@goaaats sir

**Comment by goaaats** [comment]
I was fighting through the reformat earlier, I'll try to get it merged in my lunch break tomorrow

**Comment by goaaats** [comment]
Hand-merged and reapplied the format, thanks a bunch. I added you as a co-author but GitHub doesn't seem to be showing it, apologies.

**Comment by NotNite** [comment]
Thank you! It's probably because I have GitHub vigilant mode on, but w/e, I don't care.

**Pull request closed without merging**
